import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Upperheader, { Header } from "@/components/header";
import Footer from "@/components/footer";
//import About from "@/components/about";
//import Featureblock from "@/components/featureblock";
//import Listing from "@/components/listing";



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
     <Upperheader />
     <Header />
     
                
        {children}
        <Footer />
      </body>
    </html>
  );
}
 
